# vim: set syntax=helm:

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openssh-server.fullname" . }}
  labels:
    {{- include "openssh-server.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "openssh-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "openssh-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: host-key
        secret:
          secretName: {{ .Values.hostKey.secretName }}
          defaultMode: 0640
      - name: auth
        secret:
          secretName: {{ .Values.auth.secretName }}
          defaultMode: 0640
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Values.dataPvcName }}
      - name: home
        emptyDir: {}
      initContainers:
      - name: prepare-home
        securityContext: {{- toYaml .Values.securityContext | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - sh
        - -uex
        - -c
        - |-
          mkdir -v /home/user1 && chmod -v 0700 /home/user1
          mkdir -v /home/user1/.ssh && chmod -v 0700 /home/user1/.ssh
          cp -v /secrets/auth/authorized_keys /home/user1/.ssh && chmod -v 0600 /home/user1/.ssh/authorized_keys
          cp -v /secrets/host-key/ssh_host_key /home/user1/ && chmod -v 0600 /home/user1/ssh_host_key
        volumeMounts:
        - name: host-key
          mountPath: /secrets/host-key
          readOnly: true
        - name: auth
          mountPath: /secrets/auth
          readOnly: true
        - name: home
          mountPath: /home
      containers:
      - name: sshd
        securityContext: {{- toYaml .Values.securityContext | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        workingDir: /home/user1
        env:
        - name: HOME
          value: /home/user1
        command:
        - /usr/sbin/sshd
        - -p
        - "2222"
        - -D
        - -e
        - -h
        - $(HOME)/ssh_host_key
        - -oPidFile=none
        - -oPasswordAuthentication=no
        - -oUsePAM=no
        volumeMounts:
        - name: home
          mountPath: /home
        - name: data
          mountPath: /data
          readOnly: true
        ports:
        - name: ssh
          containerPort: 2222
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
