# vim: set filetype=helm:

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-http-secret
  labels:
    {{- include "registry.labels" . | nindent 4 }}
type: Opaque
data:
  http-secret: {{ randAlphaNum 20 | b64enc | quote }}


---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-htpasswd
  labels:
    {{- include "registry.labels" . | nindent 4 }}
type: Opaque
data:
  htpasswd: {{ htpasswd (.Values.registry.user) (.Values.registry.password) | b64enc | quote }}

