# vim: set filetype=helm:

{{- $fullname := (include "geoserver.fullname" .) -}}
{{- $serviceDomain := (include "geoserver.serviceDomain" .) -}}
{{- $podname := printf "%s-0" $fullname -}}
{{- $passwordSecret := lookup "v1" "Secret" .Release.Namespace .Values.adminPassword.secretName -}}

# manifests
---
{{- if $passwordSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}-admin-netrc
data:
  netrc: {{ printf "machine %s.%s login admin password %s" $podname $serviceDomain ((get $passwordSecret "data").password | b64dec) | b64enc }}
{{- end }}{{/*if*/}}
