# vim: set filetype=helm:

apiVersion: v1
kind: Service
metadata:
  name: {{ include "geoserver.fullname" . }}
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http-alt
  selector:
    {{- include "geoserver.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "geoserver.fullname" . }}-web
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http-alt
  selector:
    {{- include "geoserver.selectorLabels" . | nindent 4 }}
