# vim: set filetype=helm:

{{/* a headless service that governs Geoserver statefulset */}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "geoserver.fullname" . }}
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http-alt
  selector:
    {{- include "geoserver.selectorLabelsForServer" . | nindent 4 }}


{{/* a service that exposes all members of Geoserver statefulset */}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "geoserver.fullname" . }}-web
  labels:
    {{- include "geoserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.geoserver.service.type | default "ClusterIP" }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http-alt
  selector:
    {{- include "geoserver.selectorLabelsForServer" . | nindent 4 }}
