apiVersion: v2
name: nextcloud-with-oidc
version: 1.0.0
appVersion: 0.1.0
description: A file sharing server that puts the control and security of your own data back into your hands.
keywords:
  - nextcloud
  - storage
  - http
  - web
  - php
#home: https://nextcloud.apps.rke2-1.dev-cineca.publicamundi.eu/
#icon: https://cdn.rawgit.com/docker-library/docs/defa5ffc7123177acd60ddef6e16bddf694cc35f/nextcloud/logo.svg
maintainers:
  - name: npappas
    email: npappas@athenarc.gr