name: CI - curl
run-name: Build container image for curl

on: 
  push:
    paths:
    - 'curl/**'
    - '.github/workflows/ci-curl.yml'
    branches:
    - 'curl'
    tags:
    - '0.*'
    - '1.*'

jobs:

  build_image:
    runs-on: ubuntu-20.04
    env:
      {}
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/metadata-action@v4
      id: meta
      with:
        images: |
          ghcr.io/opertusmundi/curl-jq
    - uses: docker/setup-buildx-action@v2
    - uses: docker/build-push-action@v4
      with:
        context: ./curl/docker/
        file: ./curl/docker/curl-jq.Dockerfile
        #buildArgs: |-
        push: true
        tags: |
          ghcr.io/opertusmundi/curl-jq:8-alpine
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

