name: CI - openssh-server
run-name: Run continuous-integration tasks for OpenSSH server

on: 
  push:
    paths:
    - 'openssh-server'
    branches:
    - 'openssh-server'
    tags:
    - '0.*'
    - '1.*'

jobs:

  build_image:
    runs-on: ubuntu-20.04
    env:
      {}
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/metadata-action@v4
      id: meta
      with:
        images: |
          ghcr.io/opertusmundi/openssh-server
    - uses: docker/setup-buildx-action@v2
    - uses: docker/build-push-action@v4
      with:
        context: ./openssh-server/docker/
        file: ./openssh-server/docker/debian.dockerfile
        build-args:
          uid: '1000'
        push: true
        tags: |
          ghcr.io/opertusmundi/openssh-server:8-debian
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

